---
collections:
  - name: ansible.controller
  - name: redhat_cop.controller_configuration
  ##linux
  - name: redhat.rhel_system_roles
  - name: community.general
  - name: containers.podman
  #ServiceNow
  - name: servicenow.itsm
  #satellite
  #- name: redhat.satellite
